### ISSUE TITLE
Cannot unmarshal string into Go struct field Config.JobCleanupDuration of type time.Duration

### ISSUE THREAD

**Issue by adriananeci** [Comcast/kuberhealthy#857] opened 2021-02-25 10:22 UTC
**Describe the bug**

Kuberhealthy cannot parse the configmap when `jobCleanupDuration` option is defined because it cannot unmarshal string into Go struct field `Config.JobCleanupDuration` of type `time.Duration`

```
time="2021-02-25T05:12:29Z" level=info msg="WARNING: Failed to read configuration file from disk: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field Config.JobCleanupDuration of type time.Duration"
```

**Steps To Reproduce**
- Start kuberhealthy with the following associated configmap
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kuberhealthy
  namespace: test
data:
  kuberhealthy.yaml: |-
    listenAddress: ":8080" # The port for kuberhealthy to listen on for web requests
    enableForceMaster: false # Set to true to enable local testing, forced master mode
    logLevel: "debug" # Log level to be used
    listenNamespace: "test" # Kuberhealthy will only monitor khcheck resources from this namespace
    jobCleanupDuration: 3m # The maximum age of khjobs before being reaped
    maxCheckPods: 1 # The maximum number of check pods in Completed state before being reaped
```
- Check the logs and you'll see a warning like
```
time="2021-02-25T05:12:29Z" level=info msg="WARNING: Failed to read configuration file from disk: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field Config.JobCleanupDuration of type time.Duration"
```
- Try to adjust `jobCleanupDuration` value in configmap
- Check kuberhealthy logs and you'll see
```
time="2021-02-25T10:07:35Z" level=debug msg="configReloader: configuration file hash has changed to: 1807f3c6108d085b5b5b6b2a87294b16"
time="2021-02-25T10:07:41Z" level=error msg="configReloader: Error reloading config: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field Config.JobCleanupDuration of type time.Duration"
```

**Expected behavior**
No warnings/errors during starting or configmap changes 

**Versions**
 - Cluster OS: Flatcar
 - Kubernetes Version: 1.18.14
 - Kuberhealthy Release: v2.4.0

**Comment by integrii** [comment] 2021-03-03 17:57
This is really strange considering that the helm chart defaults to `15m` in the [values.yaml](https://github.com/Comcast/kuberhealthy/blob/master/deploy/helm/kuberhealthy/values.yaml)... We will need to reproduce this one and figure out what the difference is

**Comment by joshulyne** [comment] 2021-04-12 18:41
Fixed in #862! Use image: `kuberhealthy/kuberhealthy:v2.4.1`!

**Comment by integrii** [comment] 2021-04-30 16:20
@joshulyne and I looked into this and it looks like the root cuase of the failed `time.Duration` parsing is due to the package used [here](https://github.com/Comcast/kuberhealthy/blob/master/cmd/kuberhealthy/config.go#L10).  I am going to open a new PR for this one here soon.  Reopening.

**Comment by integrii** [comment] 2021-04-30 16:21
Looks like I can piggyback this change into #884

**Closed** 2021-05-04 23:00 UTC
Labels: bug
