### ISSUE TITLE
Kuberhealthy memory leak

### ISSUE THREAD

**Issue by cagdascirit** [Comcast/kuberhealthy#293] opened 2020-01-26 20:25 UTC
**Describe the bug**
Kuberhealty master pod is leaking memory and when it hit its limit value it is being killed. Kuberhealthy follower pods are not suffering from this issue. This can be related to khc->podcreation->khsupdate cycle.

**Steps To Reproduce**
- Deploy kuberhealty deployment (with at least one replica) and khc objects
- Put 12 external healthchecks (for us it is 13 in total with dns-check)

**Expected behavior**
Kuberhealthy master and follower pods should not leak memory and keep going stabilized in memory usage.

**Screenshots**
[Here memory request is 300mb, memory limit is 1gb]
![Screenshot 2020-01-26 at 21 14 34](https://user-images.githubusercontent.com/2715555/73141234-23df8a00-4082-11ea-9482-624f77b57d76.png)

**Versions**
 - Cluster OS: Container Linux by CoreOS 2303.3.0 (Rhyolite)
 - Kernel Version: 4.19.86-coreos
 - Docker  Version: 18.6.3
 - Kubernetes Version: 1.14.8
 - Kuberhealthy Release: 2.0.0 (and also tested with 2.1.0rc1 same behaviour)

**Additional context**

**Comment by integrii** [comment] 2020-01-27 17:09
Whoa!  Thanks for reporting this.  I can't repro in any of our clusters.  We get charts like this:
![image](https://user-images.githubusercontent.com/98695/73196591-b749a700-40e4-11ea-9e45-a3e71174a338.png)


Can you paste me your `khcheck` definitions?  Do you see any errors at the console of either of the Kuberhealthy pods showing a memory leak?

**Comment by cagdascirit** [comment] 2020-01-29 00:47
"Do you see any errors at the console of either of the Kuberhealthy pods showing a memory leak?"
No, only some warnings like below on leader and follower pods:

> level=warning msg="was unable to find calling pod with remote IP X.X.X.X while watching for duration"

**Comment by cagdascirit** [comment] 2020-01-29 01:05
We have in total of 13 khchecks deployed. Your grafana screenshot window is too short to judge if there is a leak or not. But what I understand from your statements that on your clusters memory usage is consistent even in bigger time windows right? weird..

**Comment by integrii** [comment] 2020-01-30 03:32
I realized after posting that my chart was indeed worthless.  Here is a better one for proofsies.

![image](https://user-images.githubusercontent.com/98695/73417586-71036c00-42cd-11ea-9433-110ba1057bcb.png)

However, while looking for a bad pod, I did find one with a memory leak!

![image](https://user-images.githubusercontent.com/98695/73417721-f8e97600-42cd-11ea-924b-e88e93300200.png)

I am going to compile a debugger version and plug into it for memory stats, then get back to you.  This will probably be an emergency 1.2.1 release when we nail it down.  I'll let you know when I have a test image.

Thanks again for reporting this 👍

**Comment by cagdascirit** [comment] 2020-01-30 11:00
Better limit your kuberhealthy pod memory usage like we are doing :D

**Comment by cagdascirit** [comment] 2020-02-06 17:56
Any update on this @integrii ?

**Comment by integrii** [comment] 2020-02-07 01:01
I see a memory leaking pod, but nothing very obvious yet.  It seems like it may be a kubernetes API object watcher?  

![image](https://user-images.githubusercontent.com/98695/73991714-dd035700-4901-11ea-8c85-93ab31446c6e.png)

![image](https://user-images.githubusercontent.com/98695/73991864-4aaf8300-4902-11ea-8d60-6b15735db18a.png)

Perhaps a watch is being started somewhere and never stopped?

**Comment by integrii** [comment] 2020-02-07 01:04
If you want to run the debug version, the image is: `quay.io/comcast/kuberhealthy:2.1.0-pprof`.

To get the above reports, I port-forwarded like this:

`kubectl port-forward pod/kuberhealthy-6d4ccbc4bd-hqnzk -n kuberhealthy 8080`

Then, I opened the pprof viewer locally like this:

`go tool pprof -http localhost:8081 "http://localhost:8080/debug/pprof/heap"`

**Comment by cagdascirit** [comment] 2020-02-07 18:19
OK. We will try to use the debug version and I will share the results here

**Comment by cagdascirit** [comment] 2020-02-11 07:53
Hi @integrii we have used debug container and generated memory usage report with pprof. Exact same results with you. Highly probable that k8s Watch() operation is leaking, there must be somewhere or multiple places watcher.Stop() resource release operation is missing..

**Comment by integrii** [comment] 2020-02-19 01:09
I just searched for instances in the main kuberhealthy binary where a watch was started and ensured that things are properly closed (see commit 76c296c linked to this).  It looks like this may have been from the master status monitor never ending it's watch...  I will search other packages for more instances of watches that could be leaking as well.

**Comment by integrii** [comment] 2020-02-20 19:45
I found one more call to `Done()` that was missing, but I think this may be the root cause... see PR #317

**Comment by cagdascirit** [comment] 2020-02-23 21:42
I have cherry-picked #317 commits on our v2.1.0 but the result is still the same : (

**Comment by cagdascirit** [comment] 2020-05-08 11:31
Hi, @integrii do you still see this issue while testing 2.2.0 release candidates (i hope it will be released soon). Do you have any expectation that this issue will be fixed indirectly with other fixes and refactorings introduced for that release?

**Comment by cagdascirit** [comment] 2020-06-22 07:14
We have patched v2.2.0 with #537 content and the memory leak problem is gone!

**Comment by integrii** [comment] 2020-07-13 20:32
I am closing this because #548 is merged

**Closed by integrii** 2020-07-13 20:32 UTC
Labels: bug, in progress

**Comment by zeleena** [comment] 2020-07-14 18:41
Can v2.2.0 be patched with #548?
